#!/bin/bash

set -o errexit

declare -i PLAINTEXT=0

function usage() {
  local -r -i exitval=$1
  cat &>/dev/stderr <<USAGE
usage:
  $0 <options>
    --endpoint-hostport <host:port> host:port string
    --protoset <filename>           protobuf spec image file
    --rpc <rpc name>                rpc name
    --request <filename>            request.json filename
    --plaintext                     send plaintext request
environment variables:
    GHZ                             path to ghz executable (required)
USAGE
  # shellcheck disable=SC2086
  exit ${exitval}
}

function check_app() {
  declare -n _app=$1
  if [[ -z ${_app} ]]; then
    printf "env var [%s] is not set\n" "$1" &>/dev/stderr
    exit 1
  elif ! command -v "${_app}" >/dev/null; then
    printf "%s command [%s] not found or not executable\n" "$1" "${_app}" &>/dev/stderr
    exit 1
  fi
}

check_app GHZ

while [[ $# -gt 0 ]]; do
  case "$1" in
    --endpoint-hostport)
      ENDPOINT_HOSTPORT="$2"
      shift 2
      ;;
    --docker-network)
      printf "Ignoring arg --docker-network\n"
      shift 2 || usage
      ;;
    --rpc)
      RPC="$2"
      shift 2
      ;;
    --protoset)
      PROTOSET_FILENAME="$2"
      shift 2
      ;;
    --request)
      REQUEST_FILENAME="$2"
      shift 2
      ;;
    --plaintext)
      PLAINTEXT=1
      shift
      ;;
    --help | -h) usage 0 ;;
    *) usage 1 ;;
  esac
done

: "${RPC?"Error: --rpc must be specified"}"
: "${PROTOSET_FILENAME?"Error: --protoset must be specified"}"
: "${REQUEST_FILENAME?"Error: --request must be specified"}"
: "${ENDPOINT_HOSTPORT?"Error: --endpoint-hostport not specified"}"

declare -r REPORT_FILE=ghz_report.json
declare -r REPORT_FORMAT=pretty

declare -a GHZ_ARGS=(
  "--concurrency=10"
  "--total=5000"
  "--call=${RPC}"
  "--format=${REPORT_FORMAT}"
)
if [[ ${PLAINTEXT} -eq 1 ]]; then
  GHZ_ARGS+=("--insecure")
fi

"${GHZ}" "${GHZ_ARGS[@]}" \
  --data-file="${REQUEST_FILENAME}" \
  --protoset="${PROTOSET_FILENAME}" \
  "${ENDPOINT_HOSTPORT}" \
  >"${TEST_UNDECLARED_OUTPUTS_DIR}/${REPORT_FILE}"
