#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function run_curl() {
  declare -i http_status_code=$1
  declare -r success_message=$2
  declare -r failure_message=$3
  if [[ ${http_status_code} -ge 200 ]] && [[ ${http_status_code} -le 299 ]]; then
    printf "%s\n" "$success_message"
  else
    printf "%s\n" "$failure_message"
  fi
}

run_curl $(/proxify -- curl -o /dev/null -s -w "%{http_code}\n" https://www.google.com/) \
  "SUCCESS. Connected to outside world." \
  "FAILURE. Could not connect to outside world. Check if proxy is running."
run_curl $(/proxify -- curl -o /dev/null -s -w "%{http_code}\n" -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600") \
  "SUCCESS. Accessed AWS resource." \
  "FAILURE. Could not access AWS resource. Check if proxy is running."
/proxify -- /server/bin/validation_test
