#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


declare -r AZ=/usr/bin/az
declare -r IMAGE_TAG="mcr.microsoft.com/azure-cli:azurelinux3.0"
declare -a DOCKER_FLAGS=(
  --rm
  --entrypoint="${AZ}"
)

if [[ -v DOCKER_NETWORK ]]; then
  DOCKER_FLAGS+=("--network=${DOCKER_NETWORK}")
fi
if [[ -d ${AZURE_HOME} ]]; then
  DOCKER_FLAGS+=("--volume=${AZURE_HOME}:/root/.azure")
fi
if [[ -f ${AZURE_CERT} ]]; then
  DOCKER_FLAGS+=("--volume=${AZURE_CERT}:/azure_cert.pem")
fi
if [[ -d ${KUBE_HOME} ]]; then
  DOCKER_FLAGS+=("--volume=${KUBE_HOME}:/root/.kube")
fi
docker run \
  "${DOCKER_FLAGS[@]}" \
  "${IMAGE_TAG}" \
  "$@"
