# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "gcp_nosql_database_provider_lib",
    srcs = glob(
        [
            "*.cc",
            "*.h",
        ],
    ),
    deps = [
        "//scp/cc:cc_base_include_dir",
        "//scp/cc/cpio/client_providers/instance_client_provider/src/gcp:gcp_instance_client_provider_lib",
        "//scp/cc/cpio/client_providers/interface:cpio_client_providers_interface_lib",
        "//scp/cc/cpio/client_providers/nosql_database_client_provider/src/common:nosql_database_provider_common_lib",
        "//scp/cc/cpio/common/src/gcp:gcp_utils_lib",
        "@com_github_googleapis_google_cloud_cpp//:spanner",
        "@com_google_absl//absl/strings",
        "@nlohmann_json//:lib",
    ],
)

exports_files([
    "gcp_nosql_database_client_provider.h",
    "gcp_nosql_database_client_provider.cc",
    "gcp_nosql_database_client_utils.h",
])

filegroup(
    name = "gcp_nosql_database_client_provider_srcs",
    srcs = [
        ":gcp_nosql_database_client_provider.cc",
        ":gcp_nosql_database_client_provider.h",
        ":gcp_nosql_database_client_utils.h",
    ],
)
