# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: (?x)^(
             bazel-(bin|out|testlogs|workspace)/.*|
             builders/.*|
             version\.txt|
             .*/test_cases/.*(request|reply)\.json |
             docs/bazel/.*\.md
         )$

fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
    exclude: '^.*\.patch$'
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-json
  - id: check-symlinks
  - id: check-added-large-files
  - id: check-vcs-permalinks
  - id: check-executables-have-shebangs
  - id: detect-private-key

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: script-must-not-have-extension
  - id: script-must-have-extension
  - id: require-ascii
  - id: shellcheck
    exclude: '^(tools|google_internal)/.*$'

- repo: local
  hooks:
  - id: addlicense
    name: addlicense
    language: golang
    additional_dependencies:
    - github.com/google/addlicense@v1.0.0
    always_run: false
    pass_filenames: true
    entry: addlicense -v
    types_or:
    - text

  - id: addlicense-check
    name: addlicense check
    language: golang
    additional_dependencies:
    - github.com/google/addlicense@v1.0.0
    always_run: false
    pass_filenames: true
    entry: addlicense -check
    types_or:
    - text

- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
  - id: go-fmt
    name: go format

- repo: https://github.com/bufbuild/buf
  rev: v1.19.0
  hooks:
  - id: buf-format
  - id: buf-lint

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
  - id: prettier
    name: prettier markdown
    types_or:
    - markdown

- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.7.0
  hooks:
  - id: markdownlint-cli2
    name: lint markdown

- repo: local
  hooks:
  - id: buildifier
    name: buildifier
    description: Format bazel WORKSPACE, BUILD and .bzl files with a standard convention.
    language: golang
    additional_dependencies:
      - github.com/bazelbuild/buildtools/buildifier@5.1.0
    always_run: true
    pass_filenames: true
    types_or:
    - bazel
    entry: buildifier
    args:
    - -lint=fix
    - -mode=fix
    - -warnings=all
