# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//scp/cc:scp_internal_pkg"])

cc_library(
    name = "job_client_provider_select_lib",
    deps = select(
        {
            "//scp/cc/public/cpio/interface:aws_cpio_lib": [
                "//scp/cc/cpio/client_providers/job_client_provider/src/aws:aws_job_client_provider_lib",
            ],
            "//scp/cc/public/cpio/interface:gcp_cpio_lib": [
                "//scp/cc/cpio/client_providers/job_client_provider/src/gcp:gcp_job_client_provider_lib",
            ],
        },
        no_match_error = "Please build for AWS or GCP",
    ),
)

cc_library(
    name = "job_client_provider_lib",
    srcs = glob(
        [
            "*.cc",
            "*.h",
        ],
    ),
    deps = [
        "//scp/cc:cc_base_include_dir",
        "//scp/cc/core/common/serialization/src:serialization_lib",
        "//scp/cc/core/interface:async_context_lib",
        "//scp/cc/core/interface:interface_lib",
        "//scp/cc/core/utils/src:core_utils",
        "//scp/cc/cpio/client_providers/interface:cpio_client_providers_interface_lib",
        "//scp/cc/cpio/client_providers/interface:type_def",
        "//scp/cc/cpio/client_providers/nosql_database_client_provider/src/common:nosql_database_provider_common_lib",
        "//scp/cc/cpio/client_providers/queue_client_provider/src:queue_client_provider_select_lib",
        "//scp/cc/public/core/interface:execution_result",
        "//scp/cc/public/cpio/interface:cpio_errors",
        "//scp/cc/public/cpio/proto/job_service/v1:job_service_cc_proto",
        "@com_google_protobuf//:protobuf",
        "@nlohmann_json//:lib",
    ],
)
