# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test_http1_server",
    testonly = True,
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//scp/cc/core/interface:errors_lib",
        "//scp/cc/core/test/utils:utils_lib",
        "//scp/cc/public/core/interface:execution_result",
        "@boost//:asio",
        "@boost//:beast",
        "@com_google_absl//absl/container:btree",
    ],
)
