#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Install socat, IP command, Open SSH, strace, etc.
apt-get update
apt-get install -y iproute2 openssh-client openssh-server strace sysvinit-utils util-linux

apt-get -o 'Acquire::https::No-Cache=True' -o 'Acquire::http::No-Cache=True' update --quiet
DEBIAN_FRONTEND=noninteractive apt-get install --quiet -y --no-install-recommends curl gcc libc-dev make
mkdir -p /tmp/socat-build
cd /tmp/socat-build
curl -L http://www.dest-unreach.org/socat/download/socat-1.7.4.4.tar.gz \
  | tar -xz --strip-components=1
./configure
make -j socat
mv socat /
cd /
rm -rf /tmp/socat-build

set -o xtrace
/socat -V
ip addr add 0.0.0.0/32 dev lo
ip link set dev lo up
# Forward incoming connections from the vsock to ssh
/socat VSOCK-LISTEN:5006,reuseaddr,fork TCP:0.0.0.0:22 &
mkdir -p /run/sshd
while true; do
    /usr/sbin/sshd -d -D
done
