workspace(name = "google_privacysandbox_test_import")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "0a8003b044294d7840ac7d9d73eef05d6ceb682d7516781a4ec62eeb34702578",
    strip_prefix = "rules_python-0.24.0",
    urls = [
        "https://github.com/bazelbuild/rules_python/releases/download/0.24.0/rules_python-0.24.0.tar.gz",
    ],
)

local_repository(
    name = "google_privacysandbox_servers_common",
    path = "../..",
)

load(
    "@google_privacysandbox_servers_common//third_party:cpp_deps.bzl",
    shared_cpp_dependencies = "cpp_dependencies",
)

shared_cpp_dependencies()

load("@google_privacysandbox_servers_common//third_party:deps1.bzl", "deps1")

deps1()

load("@google_privacysandbox_servers_common//third_party:deps2.bzl", "deps2")

deps2()

load("@google_privacysandbox_servers_common//third_party:deps3.bzl", "deps3")

deps3()

load("@google_privacysandbox_servers_common//third_party:deps4.bzl", "deps4")

deps4()
