workspace(name = "google_privacysandbox_test_import")

local_repository(
    name = "google_privacysandbox_servers_common",
    path = "../..",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "8c8fe44ef0a9afc256d1e75ad5f448bb59b81aba149b8958f02f7b3a98f5d9b4",
    strip_prefix = "rules_python-0.13.0",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.13.0.tar.gz",
)

load("@google_privacysandbox_servers_common//third_party:scp_repositories.bzl", "scp_repositories")

scp_repositories()

load("@google_privacysandbox_servers_common//third_party:scp_deps.bzl", "scp_deps")

scp_deps()

load("@google_privacysandbox_servers_common//third_party:scp_deps2.bzl", "scp_deps2")

scp_deps2()
