name: "functionaltest-v2-test-sut"

stages: {
  command: {
    bazel: {
      test_targets: "//test_cases:all_tests"
    }
  }
}
stages: {
  command: {
    shell: {
      command: "./myapp"
      env { key: "SOME_TEST_VAR1" , value: "SOMETHING" }
      env { key: "SOME_TEST_VAR2" , value: "SOMETHING ELSE" }
    }
  }
}
stages: {
  command: {
    bazel: {
      test_targets: "//test_cases:all_tests"
    }
  }
}
