#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o pipefail
export TZ=Etc/UTC
export PS4='+\t $(basename ${BASH_SOURCE[0]}):${LINENO} ' # xtrace prompt

function usage() {
  local -r -i exitval=${1-1}
  cat &>/dev/stderr <<USAGE
usage:
  ${BASH_SOURCE[0]} <options>
    --run-tests                  Run tests to ensure docs are up-to-date

environment variables (all optional):
    WORKSPACE                    Set the path to the workspace (repo root)
    BAZEL_STARTUP_ARGS           Additional startup arguments to pass to bazel invocations
    BAZEL_EXTRA_ARGS             Additional command arguments to pass to bazel invocations
    EXTRA_DOCKER_RUN_ARGS        Additional arguments to pass to docker run invocations
USAGE
  # shellcheck disable=SC2086
  exit ${exitval}
}

declare -i RUN_TESTS=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --run-tests)
      RUN_TESTS=1
      shift
      ;;
    -h | --help) usage 0 ;;
    *) usage ;;
  esac
done

SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
readonly SCRIPT_DIR
readonly TOOLS_DIR="${SCRIPT_DIR}"/../builders/tools
# shellcheck disable=SC1090
source "${TOOLS_DIR}"/builder.sh

declare -a -r targets=(
  //docs/cpio/protobuf:generate_docs
)

if [[ ${RUN_TESTS} -eq 1 ]]; then
  "${TOOLS_DIR}"/bazel-debian test //docs/...
fi

for tgt in "${targets[@]}"; do
  "${TOOLS_DIR}"/bazel-debian run "${tgt}"
done
