#!/bin/bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit

printf "Checking linkage from src/experimental/ and google_internal/ \n"

if ! [[ -f /.dockerenv ]]; then
  printf "This script only runs inside a presubmit container\n"
  exit 1
fi

# Package names cannot start with a "/", so need to reference relative paths
# However, first ensure we are in the correct working dir
if [[ ${PWD} != /src/workspace ]]; then
  printf "Inside incorrect working dir: %s\n Exiting..." "$(pwd)"
  exit 1
fi

# Now that we are sure we are in /src/workspace check paths relative to
# WORKSPACE file
for directory in src/experimental/ google_internal/;
do
  target_str="attr(testonly, 0, ${directory}...)"
  output="$(bazel query "$target_str")"
  printf "target_str = %s\n output = %s\n" "${target_str}" "${output}"
  if [[ -n $output ]]; then
    cat <<EOF
There were BUILD files in ${directory}... which have not been tagged with default_testonly=True\n
${output}
In order to fix this run the following commands:
buildozer 'set default_testonly True' ${directory}...:__pkg__
buildozer 'comment code\ in\ ${directory}\ may\ only\ be\ used\ for\ testing' ${directory}/...:__pkg__
EOF
    exit 1
  fi
done

exit 0
