#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

trap cleanup EXIT
function cleanup() {
  if ! [[ -z ${server_pid+x} ]]; then
    kill ${server_pid}
  fi;
}

/proxify -- /server/bin/greeter_server --port 50051 &
declare -i -r server_pid=$!
sleep 1
declare -r greeting_output="$(/proxify -- /server/bin/greeter_client --target localhost:50051)"
declare -r greeter_test="Greeter server test from TEE."
if [[ ${greeting_output} == "Greeter received: Hello world" ]]; then
  printf "[ %s ] %s\n" SUCCESS "${greeter_test}"
else
  printf "[ %s ] %s\n" FAILURE "${greeter_test}"
fi;
sleep 5
/proxify -- /server/bin/validation
