# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_cc//cc:defs.bzl", "cc_proto_library", "cc_test")
load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//scp/cc:scp_internal_pkg"])

proto_library(
    name = "serialization_test_proto",
    srcs = ["test.proto"],
)

cc_proto_library(
    name = "test_cc_proto",
    deps = [":serialization_test_proto"],
)

cc_test(
    name = "serialization_test",
    size = "small",
    srcs = ["serialization_test.cc"],
    deps = [
        ":test_cc_proto",
        "//scp/cc:cc_base_include_dir",
        "//scp/cc/core/common/serialization/src:serialization_lib",
        "//scp/cc/core/interface:type_def_lib",
        "//scp/cc/core/test/utils:utils_lib",
        "@com_google_googletest//:gtest_main",
    ],
)
